Racker::Processor.register_template do |t|
  
  t.builders['builder'] = {
    'boot_wait'                 => '10s',
    'disk_size'                 => '{{user `disk_size_long`}}',
    'disk_type_id'              => '0',
    'guest_os_type'             => nil,
    'headless'                  => '{{ user `headless`}}',
    'iso_checksum'              => '{{user `iso_checksum`}}',
    'iso_checksum_type'         => '{{user `iso_checksum_type`}}',
    'iso_url'                   => '{{user `iso_url`}}',
    'vnc_port_min'              => 5500,
    'vnc_port_max'              => 6000,
    'http_directory'            => 'bits',
    'http_port_min'             => 20000,
    'http_port_max'             => 21000,
    'output_directory'          => 'output/{{user `bb_vm_name`}}',
    'ssh_port'                  => 22,
    'ssh_username'              => 'root',
    'ssh_password'              => 'default',
    'ssh_wait_timeout'          => '10000s',
    'shutdown_command'          =>  '{{user `shutdown_command`}}',
    'type'                      => 'vmware-iso',
    'vm_name'                   => '{{user `vm_name`}}',
    'vmx_data'                  => {
      'cpuid.coresPerSocket'          => '1',
      'ethernet0.displayname'         => 'Ethernet 0',
      'ethernet0.virtualdev'          => 'vmxnet3',
      'isolation.tools.copy.disable'  => 'FALSE',
      'isolation.tools.paste.disable' => 'FALSE',
      'memsize'                       => '2048',
      'numvcpus'                      => '2',
      'tools.synctime'                => 'FALSE',
      'scsi0.virtualdev'              => 'lsilogic',
    },
    'vmx_template_path'         => 'bits/vmx/generic.vmx',
    'vmdk_name'                 => '{{user `bb_vm_name`}}',
  }
end
