---
- hosts: all
  pre_tasks:
    - name: Check if VirtualBox is running the guest VM.
      stat: path=/root/.vbox_version
      register: virtualbox_check

    # - name: Check if VMWare is running the guest VM.
    #   shell: "cat /proc/scsi/scsi | grep VMware"
    #   changed_when: false
    #   failed_when: false
    #   register: vmware_check

  roles:
    - ca-certificates
    - sshd
    - vagrant
    - { role: virtualbox-guest, when: virtualbox_check.stat.exists }
    - minimize-os
