---
  - name: Get the current list of installed packages
    shell: dpkg-query -l > /tmp/pre-virtualbox-guest-packages.txt

  - name: Install necessary packages for compiling
    apt:
      name={{ item }}
      update_cache=yes
      install-recommends=no
      state=present
    with_items:
      - bzip2
      - dkms
      - gcc
      - make

  - name: Get the packages installed after bringing in the necessary ones
    shell: dpkg-query -l > /tmp/post-virtualbox-guest-packages.txt

  - name: Determine what packages were actually installed
    shell: diff /tmp/pre-virtualbox-guest-packages.txt /tmp/post-virtualbox-guest-packages.txt|awk '/>/{print $3}'
    register: installed

  - name: Mount VirtualBox guest additions ISO.
    mount:
      name: /tmp/vbox
      src: /root/VBoxGuestAdditions.iso
      opts: loop
      state: mounted
      fstype: iso9660

  - name: Run VirtualBox guest additions installation.
    shell: sh /tmp/vbox/VBoxLinuxAdditions.run --nox11
    failed_when: false

  - name: Unmount VirtualBox guest additions ISO.
    mount:
      name: /tmp/vbox
      src: /root/VBoxGuestAdditions.iso
      state: absent
      fstype: iso9660

  - name: Delete VirtualBox guest additions ISO.
    file:
      path: /root/VBoxGuestAdditions.iso
      state: absent

  - name: Remove diff files
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - /tmp/pre-virtualbox-guest-packages.txt
      - /tmp/post-virtualbox-guest-packages.txt
  
  - name: Remove installed packages for compiling
    apt:
      name="{{ installed.stdout_lines }}"
      state=absent
      update_cache=yes
      cache_valid_time=86400
      autoremove=yes
      purge=yes
    