---
  - name: 
    file:
      path: /mnt/hgfs
      state: directory

  - name: Install necessary packages
    apt:
      name={{ item }}
      update_cache=yes
      install-recommends=no
      state=present
    with_items:
      - open-vm-tools
      - fuse
