---
- name: Create vagrant user .ssh directory
  file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Copy vagrant user authorized_keys file
  copy:
    src: "{{ role_path }}/files/authorized_keys"
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Copy vagrant user sudoers file
  copy:
    src: "{{ role_path }}/files/sudoers"
    dest: /etc/sudoers.d/vagrant